[package]
name = "sp-transaction-pool"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0" }
derive_more = "0.15.0"
futures = { version = "0.3.0", features = ["thread-pool"] }
log = "0.4.8"
parking_lot = "0.9.0"
primitives = { package = "substrate-primitives",  path = "../core" }
sr-api = { path = "../sr-api" }
sr-primitives = { path = "../sr-primitives" }
tx-runtime-api = { package = "substrate-transaction-pool-runtime-api", path = "./runtime-api" }
txpool = { package = "sp-transaction-graph", path = "./graph" }

[dev-dependencies]
keyring = { package = "substrate-keyring", path = "../keyring" }
test-client = { package = "substrate-test-runtime-client", path = "../../test/utils/runtime/client" }
